name: abstraction_CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  CPU-Tests:
    name: CPU-Tests
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/exawind-snapshot
      env:
          SPACK_MANAGER: /spack-manager
          E4S_MACHINE: true
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{github.token}}
      - name: Clone
        uses: actions/checkout@v3
        with:
          path: main
      - name: Setup Dependencies
        run: |
          /bin/bash -c " \
          source ${SPACK_MANAGER}/start.sh && \
          spack-start && \
          spack install kokkos amrex googletest \
          "
      - name: Test
        working-directory: ${GITHUB_WORKSPACE}
        run: |
          /bin/bash -c " \
          source ${SPACK_MANAGER}/start.sh && \
          spack-start && \
          spack load kokkos amrex googletest && \
          mkdir build && \
          cd build && \
          cmake ../ -DENABLE_KOKKOS_TESTS -DENABLE_AMREX_TESTS && \
          make -j $(nproc) && \
          ./test_stl && \
          ./test_amrex && \
          ./test_kokkos && \
          "


        

